### ISSUE TITLE
Improve performance 

### ISSUE THREAD

**Issue by loverdeveloper** [codrops/InteractiveLandscape#2]
Work hard on this project performance, it's really **important**

**Comment by ma77os** [comment]
Hi @loverdeveloper, thanks for the feedback.
I'd like to let you know this was created for a tutorial in order to demonstrate a specific visual concept and tecnique, it wasn't meant necessarly to be super optimized / tested for production, altough it runs very smoothly in modern desktop and mobile devices.
Anyway let me know if you would like to suggest something that not worked for you and feel free to submit a pull request.
